// <auto-generated />
namespace STOshopService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class REport_step2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(REport_step2));
        
        string IMigrationMetadata.Id
        {
            get { return "201805291653584_REport_step2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
